source "https://rubygems.org"

ruby "3.2.0"

# Rails
gem "rails", "~> 7.0.0"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"

# EZLogs Ruby Agent
gem "ezlogs_ruby_agent", path: "../.."

# Development and test gems
group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 3.0"
  gem "simplecov", "~> 0.21"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "web-console", "~> 4.0"
end

group :test do
  gem "capybara", "~> 3.35"
  gem "selenium-webdriver", "~> 4.0"
  gem "webdrivers", "~> 5.0"
end 