inherit_from: .rubocop_todo.yml

# Add custom cops that align with .cursorrules
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'