# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ezlogs_ruby_agent/protobuf/event.proto

require 'google/protobuf'


descriptor_data = "\n*lib/ezlogs_ruby_agent/protobuf/event.proto\x12\x06\x65zlogs\"\x92\x02\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x10\n\x08resource\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12-\n\x08metadata\x18\x08 \x03(\x0b\x32\x1b.ezlogs.Event.MetadataEntry\x12\x15\n\rerror_message\x18\t \x01(\t\x12\x10\n\x08\x64uration\x18\n \x01(\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Ezlogs
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ezlogs.Event").msgclass
end
